NAME=adpcm
LOCAL_CONFIG = -legup-config=config.tcl

#ifeq ($(NO_OPT),)
 #   NO_OPT=1
#endif
#ifeq ($(NO_INLINE),)
 #   NO_INLINE=1
#endif

LEVEL = ../../../..
include ../../../Makefile.common
include $(LEVEL)/Makefile.common
